export const games = [
  { id: 1, name: 'Lucky 777', image: '/games/lucky-777.jpg', category: 'popular' },
  { id: 2, name: 'Golden Fortune', image: '/games/golden-fortune.jpg', category: 'popular' },
  { id: 3, name: 'Dragon Fire', image: '/games/dragon-fire.jpg', category: 'popular' },
  { id: 4, name: 'Paradise Beach', image: '/games/paradise-beach.jpg', category: 'popular' },
  { id: 5, name: 'Wild West', image: '/games/wild-west.jpg', category: 'popular' },
  { id: 6, name: 'Mystical Moon', image: '/games/mystical-moon.jpg', category: 'popular' },
  { id: 7, name: 'Roulette King', image: '/games/roulette-king.jpg', category: 'providers' },
  { id: 8, name: 'Diamond Rush', image: '/games/diamond-rush.jpg', category: 'providers' },
  { id: 9, name: 'Viking Gold', image: '/games/viking-gold.jpg', category: 'providers' },
  { id: 10, name: 'Egyptian Treasure', image: '/games/egyptian-treasure.jpg', category: 'providers' },
  { id: 11, name: 'Black Jack Pro', image: '/games/black-jack-pro.jpg', category: 'providers' },
  { id: 12, name: 'Poker Master', image: '/games/poker-master.jpg', category: 'providers' },
  { id: 13, name: 'Fruit Party', image: '/games/fruit-party.jpg', category: 'collections' },
  { id: 14, name: 'Sweet Bonanza', image: '/games/sweet-bonanza.jpg', category: 'collections' },
  { id: 15, name: 'Space Adventure', image: '/games/space-adventure.jpg', category: 'collections' },
  { id: 16, name: 'Book of Gods', image: '/games/book-of-gods.jpg', category: 'collections' },
  { id: 17, name: 'Jungle Wild', image: '/games/jungle-wild.jpg', category: 'collections' },
  { id: 18, name: 'Lucky Dragon', image: '/games/lucky-dragon.jpg', category: 'collections' },
  { id: 19, name: 'Treasure Island', image: '/games/treasure-island.jpg', category: 'new' },
  { id: 20, name: 'Night Club', image: '/games/night-club.jpg', category: 'new' },
  { id: 21, name: 'Enchanted Forest', image: '/games/enchanted-forest.jpg', category: 'new' },
  { id: 22, name: 'Crypto Kings', image: '/games/crypto-kings.jpg', category: 'new' },
  { id: 23, name: 'Lucky Cat', image: '/games/lucky-cat.jpg', category: 'new' },
  { id: 24, name: 'Rainbow Fortune', image: '/games/rainbow-fortune.jpg', category: 'new' },
  { id: 25, name: 'Live Roulette', image: '/games/live-roulette.jpg', category: 'live' },
  { id: 26, name: 'Baccarat Elite', image: '/games/baccarat-elite.jpg', category: 'live' },
  { id: 27, name: 'Premium Slots', image: '/games/premium-slots.jpg', category: 'live' },
  { id: 28, name: 'Mega Spins', image: '/games/mega-spins.jpg', category: 'live' },
  { id: 29, name: 'Jackpot Rush', image: '/games/jackpot-rush.jpg', category: 'live' },
  { id: 30, name: 'VIP Experience', image: '/games/vip-experience.jpg', category: 'live' },
  { id: 31, name: 'Lucky Spin', image: '/games/lucky-spin.jpg', category: 'slots' },
  { id: 32, name: 'Wild Symbols', image: '/games/wild-symbols.jpg', category: 'slots' },
  { id: 33, name: 'Fortune Wheel', image: '/games/fortune-wheel.jpg', category: 'slots' },
  { id: 34, name: 'Crystal Vault', image: '/games/crystal-vault.jpg', category: 'slots' },
  { id: 35, name: 'Paradise Party', image: '/games/paradise-party.jpg', category: 'slots' },
  { id: 36, name: 'Sun & Moon', image: '/games/sun-moon.jpg', category: 'slots' },
  { id: 37, name: 'Magic Mirror', image: '/games/magic-mirror.jpg', category: 'slots' },
  { id: 38, name: 'Royal Palace', image: '/games/royal-palace.jpg', category: 'slots' },
  { id: 39, name: 'Ocean Treasure', image: '/games/ocean-treasure.jpg', category: 'slots' },
  { id: 40, name: 'Fire Dragon', image: '/games/fire-dragon.jpg', category: 'slots' },
  { id: 41, name: 'Lucky Clover', image: '/games/lucky-clover.jpg', category: 'slots' },
  { id: 42, name: 'Midnight Mystery', image: '/games/midnight-mystery.jpg', category: 'slots' },
];

export const sections = [
  { id: 'popular', title: 'Покори бонусную', games: games.filter(g => g.category === 'popular') },
  { id: 'providers', title: 'Провайдеры', games: games.filter(g => g.category === 'providers') },
  { id: 'collections', title: 'Коллекции', games: games.filter(g => g.category === 'collections') },
  { id: 'new', title: 'Новички', games: games.filter(g => g.category === 'new') },
  { id: 'live', title: 'Live казино', games: games.filter(g => g.category === 'live') },
  { id: 'slots', title: 'Слоты', games: games.filter(g => g.category === 'slots') },
];
